name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: docker login --username=$DOCKER_USER --password-stdin=$DOCKER_PASSWORD
          
      - name: Build the Docker image
        working-directory: client
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        
      - name: Docker Push
        working-directory: client
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cashmanagement:latest
