name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: client
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - uses: actions/checkout@v2
      name: Check out code
   
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build and Push Docker Image
      with:
        image: vitalyevich/cashmanagement
        tags: v1, latest
        registry: registry-url.io
        dockerfile: Dockerfile.ci
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
